version: '3.9'
services:
  frontend:
    environment:
      TZ: "America/New_York"
      env: "${env:-development}"
    container_name: frontend
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "3000:3000"